//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campus.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Campus.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update email and personal info.
        /// </summary>
        public static string AccountDetailsDesc {
            get {
                return ResourceManager.GetString("AccountDetailsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        public static string AccountDetailsTitle {
            get {
                return ResourceManager.GetString("AccountDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT MANAGEMENT.
        /// </summary>
        public static string AccountManagement {
            get {
                return ResourceManager.GetString("AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editorial light or night mode.
        /// </summary>
        public static string AppThemeDesc {
            get {
                return ResourceManager.GetString("AppThemeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Theme.
        /// </summary>
        public static string AppThemeTitle {
            get {
                return ResourceManager.GetString("AppThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT PROFILE.
        /// </summary>
        public static string EditProfileButton {
            get {
                return ResourceManager.GetString("EditProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App display language.
        /// </summary>
        public static string LanguageDes {
            get {
                return ResourceManager.GetString("LanguageDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive campus reminders.
        /// </summary>
        public static string NotificationsDesc {
            get {
                return ResourceManager.GetString("NotificationsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsTitle {
            get {
                return ResourceManager.GetString("NotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and biometric access.
        /// </summary>
        public static string SecurityDesc {
            get {
                return ResourceManager.GetString("SecurityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SecurityTitle {
            get {
                return ResourceManager.GetString("SecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM &amp; PRIVACY.
        /// </summary>
        public static string SystemPrivacy {
            get {
                return ResourceManager.GetString("SystemPrivacy", resourceCulture);
            }
        }
    }
}
